services:
  backend:
    build: ./backend
    container_name: rio-inventar-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/code
    # --- HIER IST DIE ANPASSUNG ---
    environment:
      # Diese Zeile bleibt für die FastAPI-App
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Diese Zeilen fügen wir hinzu, damit Alembic sie lesen kann
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: rio-inventar-frontend
    env_file:
      - .env
    environment:
      - VITE_AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - VITE_AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: rio-inventar-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Diese Werte kommen jetzt direkt aus der .env-Datei
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data: